### ISSUE TITLE
Make "npm" key optional

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#208]
From a [discussion thread](https://github.com/notion-cli/notion/pull/181#discussion_r237960057) in #181, we should make the `"npm"` key optional and default to whatever npm version comes by default with the specified version of Node. Whenever we write to `package.json`, we should prefer to omit the key if the version matches, to encourage minimal syntax.

Depends on #181.

**Comment by charlespierce** [comment]
After a quick investigation, I think that implementing this cleanly depends on #169. Essentially what we want to do is make the Platform Specification allow the `npm` version to be optional, but then resolve that to the default version of npm.

However, currently we don't have a differentiation between Platform Spec and Image, so we run into a timing issue: If the npm version isn't specified, then we need to replace it with the default. When we are parsing `package.json`, there's no guarantee that we know what the default `npm` version is, since we might not yet have downloaded to specified version of `node`. So we really need to wait until we call `Session::prepare_image` before we lock in the version of `npm`, but `Session::prepare_image` requires the `Image` to execute.

After #169 is implemented, however, we can just make that resolution part of the `Platform::checkout` method, since we are making that separation between specification and resolved image.
