### ISSUE TITLE
rustfmt

### ISSUE THREAD

**Issue by dherman** [notion-cli/notion#243]
From https://github.com/notion-cli/notion/pull/187#issuecomment-455324948 :

> Now that [Rust has stable rustfmt built-in](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html#new-tools), I think we should do this slightly differently:
> 
> - Delete `rustfmt.sh`
> - Change the minimum Rust requirement to 1.31
> - Have the CI do `rustup component add rustfmt` and then `cargo fmt --all -q -- --check`
> - Update the README's contribution section to state the minimum Rust requirement and the requirement to do `cargo fmt` as above
> 
> We probably want to merge a couple of the larger PRs in the queue before doing this so there's not _too_ much rebasing churn.

**Comment by dherman** [comment]
Also a note that if people have trouble upgrading and getting rustfmt installed, this worked for me:

https://github.com/rust-lang/rustup.rs/issues/1558#issuecomment-452110409

**Comment by charlespierce** [comment]
I can't speak for other editors, but I do know that VS Code's Rust plugin will let you enable `Format on Save` and then call `cargo fmt` for any file as you save it. This makes it easy to keep everything formatted correctly because you don't even have to run extra commands before committing, it just happens as you save.
