### ISSUE TITLE
Support `notion install node lts`

### ISSUE THREAD

**Issue by gibfahn** [notion-cli/notion#255]
Looks like an awesome tool, thanks!

One nice thing `nvm` gives you is the ability to default to LTS versions of Node. Most people probably want to be on latest LTS by default, so it would maybe even make sense to make `notion install node` install the latest LTS by default.

In any case an opt-in flag would be useful.

nvm docs link: https://github.com/creationix/nvm#long-term-support

**Comment by chriskrycho** [comment]
This is a great suggestion – thank you for raising it!

**Comment by willsoto** [comment]
I would be interested in taking this if it seems like a reasonable thing to implement at this time.

**Comment by charlespierce** [comment]
@willsoto Absolutely, we'd welcome the contribution! Feel free to reach out if you have questions.

**Comment by willsoto** [comment]
Great! I actually wanted to go over my strategy for this after looking at the codebase for a bit (keep in mind I haven't done much Rust).

It seems like [`FetchResolve`](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/inventory/mod.rs#L132) contains all the functions necessary in order to resolve a given version, provided a version or some shorthand (e.g. `latest`, `lts`).

I was planning on adding a function to this trait called `resolve_lts` with the following signature:

```rust
fn resolve_lts(
    &self,
    name: String,
    hooks: Option<&ToolHooks<D>>,
) -> Fallible<D::ResolvedVersion>;
```

The [Node.js index.json](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/inventory/mod.rs#L54-L56) contains a property `lts: bool` which tells us which version is considered lts. 

My plan was to check that field in `resolve_lts` (probably [here](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/inventory/mod.rs#L267-L269)).

In order for this to work, I'd need to add `Lts` to [this enum](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/version/mod.rs#L14-L18). An `else if` [here](https://github.com/notion-cli/notion/blob/master/crates/notion-core/src/version/mod.rs#L59) checking for the string "lts" and an additional match [here](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/inventory/mod.rs#L150-L158) to cover the new `VersionSpec::Lts` enum value.

I think there are probably a few details that I am missing, but that is the general idea. How does that sound?

**Comment by charlespierce** [comment]
@willsoto That sounds like a great approach! The only comment I have is that you'll need to decide what the behavior of `resolve_lts` will be for `YarnCollection` and `PackageCollection`, since they also implement the `FetchResolve` trait). As Yarn and packages in the npm registry don't have a concept of Long-Term Support the same way that Node does, there are two options that come to mind:

1. Return an error. This matches the current behavior since `lts` is not a valid version, so doing `notion install yarn lts` currently would result in a parse error trying to convert the version.

2. Treat `lts` exactly the same as `latest`, proxying the call out to `resolve_latest`. This has the benefit of always working, even if it is slightly inaccurate.

Overall, I would lean towards the latter, as that would allow you to update the `Default` implementation of `VersionSpec` [here](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/version/mod.rs#L30), making LTS the default instead of Latest. That seems more ergonomic for Node, my intuition is most people will want to use LTS, and those who absolutely want the bleeding-edge would be okay with opting-in using `notion install node latest`.

**Comment by willsoto** [comment]
@charlespierce That is exactly the thought I had actually (2). I'll go ahead and open a PR at some point this weekend and we can go over the implementation in more detail.

One question I do have is where would I add the `lts` property to the structure being passed around that represents the result of `index.json`? I see [this](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/inventory/serial.rs#L113-L130). Is it as easy as adding  `lts: entry.lts,` to `NodeEntry`?

**Comment by charlespierce** [comment]
It's almost that simple, yes. You'll also need to update the two definitions of `NodeEntry` ([here](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/inventory/serial.rs#L104) and [here](https://github.com/notion-cli/notion/blob/6cc5fb3f8c020268f27b57cc2ad16eec5129e675/crates/notion-core/src/inventory/mod.rs#L511)) to add `pub lts: bool`.
