### ISSUE TITLE
Improve the error message with invalid package.json

### ISSUE THREAD

**Issue by thoov** [notion-cli/notion#358]
### Steps to Reproduce

1. Inside of an existing project, create a malformed `package.json`.
2. Run: `notion install ember-cli` (any notion command will work)
3. Encounter incorrect error message

### Actual result:

```
error: Could not parse project manifest
at /private/tmp/foobaz/package.json

Please ensure that the file is correctly formatted.
Error details written to: notion-error-2019-04-16_23_00_10.847.log
```

### Expected result:

``` 
error: Could not parse project manifest at /private/tmp/foobaz/package.json

Please ensure that the file is correctly formatted.
Error details written to: <FULL_PATH_TO_FILE>/notion-error-2019-04-16_23_00_10.847.log
```

Encountered this with notion v0.3.0

**Comment by charlespierce** [comment]
For the first issue, the newline is there for reasons of line length and wanting to make sure that arbitrary paths / urls aren't stuck onto the end of a line where they are likely to wrap. If it's more consistent with other tools and users aren't as worried about a path being cut in half because of wrapping, I can see switching it.

For the full path to the error log, I agree. I went back and forth on showing it, for similar stylistic reasons, but I think ultimately the bad UX of going "Okay great, where is that file?" is worse than the potential of a line being wrapped in the middle of a path.
