### ISSUE TITLE
Improve `yarn global add ember-cli` error message

### ISSUE THREAD

**Issue by thoov** [notion-cli/notion#360]
Running `yarn global add ember-cli` produces:

```
Notion error: Global package installs are not recommended.

Use `notion install` to add a package to your toolchain (see `notion help install` for more info).
```

Couple of thoughts:
1. It seems like most errors start with just `error` and not `Notion error`. We should be consistent.
2. Should we change the wording of `error: Global package installs are not recommended.` to something stronger (since the is an error) `error: Global package installs via yarn are not allowed.`?
3. It would be great if the message about `Use 'notion install'` was changed to `Use 'notion install ember-cli'` so that users can copy and paste the correct command.

Encountered this with notion v0.3.0.

cc: @dherman @charlespierce @mikrostew

**Comment by charlespierce** [comment]
For 1: The logic behind `Notion error` vs `error` is based on what command is being run. When you run `notion ...`, you are explicitly calling Notion, so you know that any errors are in the context of using Notion. When you run `yarn global add ember-cli`, you are running `yarn`, so if you see `error: ...`, the first thought would be "yarn had an error", instead of "Notion had an error". We wanted to be explicit when you are running a tool that isn't Notion that the error came from us, instead of from the tool itself.

For 2: I agree, we can change that message to better explain why we error. Especially since in testing, they never really worked with our inventory model, we can just explain that they aren't supported.

For 3: Agreed 100%

**Comment by thoov** [comment]
@charlespierce Im confused about your reasoning about #1.

> When you run notion ..., you are explicitly calling Notion, so you know that any errors are in the 
> context of using Notion. When you run yarn global add ember-cli, you are running yarn, so if you 
> see error: ...,

I was calling `yarn` and not `notion` yet the `Notion error` appeared.

As an aside I feel that there is also a "capitalization mismatch" going on. If we are going to have different error labels then they should be: "Notion error:" & "Error:" or "notion error:" & "error:". There is also the "clause:" label that --verbose currently adds and that as well should be in alignment with whatever capitalization we choose.

**Comment by chriskrycho** [comment]
@thoov there's also a previous discussion around capitalization: we use "Notion" for the name of the tool; the error formatting here falls out from that.

**Comment by thoov** [comment]
@chriskrycho Was the discussion in discord or do you have a link to it by chance?

**Comment by chriskrycho** [comment]
It was in Discord, but I was able to find it: [here](https://discordapp.com/channels/413753499835301908/413753499835301917/543229222689177610).

**Comment by charlespierce** [comment]
Yeah, that's exactly the idea behind it: You weren't calling `notion` directly, so without some sort of context it's not immediately obvious that the error came from Notion rather than `yarn`.

One option is to always show `Notion error`, but there was some concern that if you run `notion ...` and see `Notion error:`, it might be redundant: Of course it's a Notion error, that's what I ran.

**Comment by thoov** [comment]
@charlespierce I see what you mean now.

Thanks @chriskrycho. I will read up on that discussion
