### ISSUE TITLE
notion install @sentry/craft fails

### ISSUE THREAD

**Issue by mitsuhiko** [notion-cli/notion#385]
from the error log after running the installed `craft`:

```
cause: Directory not empty (os error 66)
```

This is with notion 0.3.0

**Comment by charlespierce** [comment]
Hi @mitsuhiko, is that error from running `craft`, or from running `notion install @sentry/craft` a second time? Could you paste the full log, including the initial error message?

I'm not seeing that error, though I am seeing that running `craft` fails due to #351 . We also had an issue, that has since been fixed (but not included in a release yet) where you would see the `Directory not empty` error when attempting to re-install the same package a second time (#352 & #353)

**Comment by mitsuhiko** [comment]
This is from installing craft but i'm not sure if that happens on the first installation. In either case though I cannot run craft due to #351.
