### ISSUE TITLE
notion which is not aware of installed bins

### ISSUE THREAD

**Issue by rwjblue** [notion-cli/notion#391]
`notion which` seems unaware of any `notion install`ed tools other than `node`/`yarn`/`npm`.

Steps to reproduce:

```
notion install node
notion install yarn
notion install ember-cli
```

```
❯ notion which node
/Users/rjackson/.notion/tools/image/node/12.1.0/6.9.0/bin/node

❯ notion which yarn
/Users/rjackson/.notion/tools/image/yarn/1.15.2/bin/yarn

❯ notion which ember

```

**Comment by chriskrycho** [comment]
Started poking at this; branch exists [here](https://github.com/chriskrycho/notion/blob/make-which-work/src/command/which.rs).

**Comment by chriskrycho** [comment]
@mikrostew @charlespierce so I've started digging into this, and it *looks* like we should just be able to include `~/.volta/bin` (doing the lookup appropriately, not hard-coding it, of course) in the user's path when resolving tools so that this works? Is there anything I'm missing there?

**Comment by charlespierce** [comment]
The issue there is that `~/.volta/bin` is the directory all the _shims_ are installed in, so that would result in the same output as you would get from e.g. `which ember`. To point to the actual binary that will get executed, we'll need to include the path from the bin config file.

The other complication is that we _probably_ want to do the correct resolution of project-local bins if we are in a project, otherwise use the globally installed version, so we likely need to recreate the logic used [here](https://github.com/notion-cli/notion/blob/57491aff83768b1c19e4c9a680479358849d11af/crates/volta-core/src/tool/binary.rs#L9), but instead of getting a `command` out of it, we get an `Option<OsString>`. Then if the result of that is `Some`, we can output the value directly, and if not, we can use the existing `volta which` logic to unwrap the rest of the system.

**Comment by chriskrycho** [comment]
That's exactly the kind of context I was lacking – thank you!

**Comment by charlespierce** [comment]
Oh, actually thinking on it more, there's an extra wrinkle that we actually only want to do this complicated logic if we have the named binary installed through `volta install`, so the logic might actually be inverted from that `tool::binary::command` does:

1. Determine if we have a user tool with that name installed, using `session.get_user_tool`
2. If we do, check if we're in a project and that project has this tool locally with `project.has_direct_bin`
3. If that's also true, we can return `path_to_bin` defined in the same way as above.
4. If not, return `user_tool.bin_path` to show the default binary.
5. If we don't have a user tool with that name, then use the existing `notion which` logic.

**Comment by chriskrycho** [comment]
Excellent! I'll see if I can get that implemented tomorrow!
